name: Mirror TUF targets
description: Used to mirror TUF targets from a source to a destination
inputs:
  metadata:
    description: source metadata location
    default: https://docker.github.io/tuf-staging/metadata
    required: true
  source:
    description: source targets location
    default: https://docker.github.io/tuf-staging/targets
    required: true
  destination:
    description: destination targets location
    required: true
    default: docker://docker/tuf-targets
  flags:
    description: flags to pass to the go-tuf-mirror command
    required: false
    default: ""
runs:
  using: docker
  image: docker://docker/go-tuf-mirror@sha256:7c4568ae29a6356ce249420b1e229af6f00c0b0c2db3f3abb7a49897d2c08fbc # v0.1.2
  args:
    - targets
    - ${{ inputs.flags }}
    - --metadata
    - ${{ inputs.metadata }}
    - --source
    - ${{ inputs.source }}
    - --destination
    - ${{ inputs.destination }}
  env:
    DOCKER_CONFIG: /github/workspace/.docker
