name: Mirror TUF metadata
description: Used to mirror TUF metadata from a source to a destination
inputs:
  source:
    description: source metadata location
    default: https://docker.github.io/tuf/metadata
    required: true
  destination:
    description: destination metadata location
    required: true
    default: docker://docker/tuf-metadata:latest
  tuf-root:
    description: embedded TUF root (dev, staging, or prod)
    default: "prod"
  flags:
    description: flags to pass to the go-tuf-mirror command
    required: false
    default: ""
runs:
  using: docker
  image: docker://docker/go-tuf-mirror@sha256:1c3d080f9989832c6205b1a8458dfcd8c07fb9f7b02727f2fe5334cdd9de08fb # v0.1.7
  args:
    - metadata
    - ${{ inputs.flags }}
    - --source=${{ inputs.source }}
    - --destination=${{ inputs.destination }}
    - --tuf-root=${{ inputs.tuf-root }}
  env:
    DOCKER_CONFIG: /github/workspace/.docker
