name: Mirror TUF metadata
description: Used to mirror TUF metadata from a source to a destination
inputs:
  source:
    description: source metadata location
    default: https://docker.github.io/tuf/metadata
    required: true
  destination:
    description: destination metadata location
    required: true
    default: docker://docker/tuf-metadata:latest
  tuf-root:
    description: embedded TUF root (dev, staging, or prod)
    default: "prod"
  flags:
    description: flags to pass to the go-tuf-mirror command
    required: false
    default: ""
runs:
  using: docker
  image: docker://docker/go-tuf-mirror@sha256:7b978d73ad627d980020cea03ef8095b2302fdf5cc20f2ec34cf5ee18a09c768 # v0.1.10
  args:
    - metadata
    - ${{ inputs.flags }}
    - --source=${{ inputs.source }}
    - --destination=${{ inputs.destination }}
    - --tuf-root=${{ inputs.tuf-root }}
  env:
    DOCKER_CONFIG: /github/workspace/.docker
