name: Mirror TUF metadata
description: Used to mirror TUF metadata from a source to a destination
inputs:
  source:
    description: source metadata location
    default: https://docker.github.io/tuf/metadata
    required: true
  targets:
    description: source targets location
    default: https://docker.github.io/tuf/targets
    required: true
  destination:
    description: destination metadata location
    required: true
    default: docker://docker/tuf-metadata:latest
  tuf-root:
    description: embedded TUF root (dev, staging, or prod)
    default: "prod"
  flags:
    description: flags to pass to the go-tuf-mirror command
    required: false
    default: ""
runs:
  using: docker
  image: docker://docker/go-tuf-mirror@sha256:0a9922d21252786c8f073e71d3f2dfd05af271c8676d2d7629c0c120aada3c3b # v0.2.1
  args:
    - metadata
    - ${{ inputs.flags }}
    - --targets=${{ inputs.targets }}
    - --source=${{ inputs.source }}
    - --destination=${{ inputs.destination }}
    - --tuf-root=${{ inputs.tuf-root }}
  env:
    DOCKER_CONFIG: /github/workspace/.docker
