name: Mirror TUF metadata
description: Used to mirror TUF metadata from a source to a destination
inputs:
  source:
    description: source metadata location
    default: https://docker.github.io/tuf-staging/metadata
    required: true
  destination:
    description: destination metadata location
    required: true
    default: docker://docker/tuf-metadata:latest
  flags:
    description: flags to pass to the go-tuf-mirror command
    required: false
    default: ""
runs:
  using: docker
  image: docker://docker/go-tuf-mirror@sha256:2e69c9835dd33dc5fdc73336bb5822b2e0358469bf4bd45ae55907ef97ab8f46 # v0.1.6
  args:
    - metadata
    - ${{ inputs.flags }}
    - --source
    - ${{ inputs.source }}
    - --destination
    - ${{ inputs.destination }}
  env:
    DOCKER_CONFIG: /github/workspace/.docker
