name: test code
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  golang:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GOPRIVATE: github.com/docker/attest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@ad38cffc07bac6e3857755914c4c88bfd2db4da4 # v1.10.2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.DOCKER_READ_APP_PRIVATE_KEY }}
          repositories: "attest,go-tuf-mirror"
      - name: Set git to use LF
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - run: |
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com".insteadOf "https://github.com"
      - name: go test
        run: |
          go test ./...
