name: Run go-tuf-mirror
on:
  workflow_run:
    workflows: ["TUF-on-CI publish"]
    types:
      - completed
    branches:
      - publish
  workflow_dispatch:
  pull_request:
env:
  DOCKER_CONFIG: ${{ github.workspace }}/.docker
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify go-tuf-mirror image attestations
        uses: docker/image-signer-verifier/actions/verify@268a8c6b4084a1dddb60c7ea058e79f6bf784eeb # v0.5.5
        with:
          signed-image-path: docker://docker/go-tuf-mirror@sha256:d4fb86ee5c94150be7adbcf6e82004f9baafe740de3c40b6e77d58bd639b5dfb # v0.1.9
          # use http since this is the mirror to OCI workflow
          tuf-source: http
          tuf-metadata: https://docker.github.io/tuf-staging/metadata
          tuf-targets: https://docker.github.io/tuf-staging/targets
          tuf-root: staging
  mirror:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dockerpublicbot
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.DOCKER_READ_APP_PRIVATE_KEY }}
          repositories: "attest,go-tuf-mirror"
      - name: Mirror metadata
        uses: docker/go-tuf-mirror/actions/metadata@update-attest-016
        with:
          source: https://docker.github.io/tuf-staging/metadata
          destination: docker://docker/tuf-metadata-staging:latest
          tuf-root: staging
          flags: "-f"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Mirror targets
        uses: docker/go-tuf-mirror/actions/targets@update-attest-016
        with:
          metadata: https://docker.github.io/tuf-staging/metadata
          source: https://docker.github.io/tuf-staging/targets
          destination: docker://docker/tuf-targets-staging
          tuf-root: staging
          flags: "-f"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
